name: Deploy to GitHub Pages

on:
  # Ejecutar en commits a master
  push:
    branches: [ master ]
  # Permite ejecutarlo manualmente
  workflow_dispatch:

# Definir permisos para deploy
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir un solo despliegue concurrente
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build with GitHub Pages configuration
        run: npm run build:github
        env:
          GITHUB_PAGES: true
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        # Actualizado a la versión v4
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
          
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4